name: Build Plugin Package

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+.[0-9]'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag (e.g., nightly-20241227)'
        required: true
        type: string
        default: 'nightly'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Decide version (tag or input)
      - name: Set version
        id: vars
        run: |
          if [[ "${{ github.event_name }}" == "push" ]]; then
            echo "version=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
          else
            echo "version=${{ inputs.version }}" >> $GITHUB_OUTPUT
          fi

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: mbstring, xml
          tools: composer:v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Clear composer cache
        run: composer clear-cache

      - name: Install Composer dependencies
        run: composer install --no-dev

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install NPM dependencies
        run: npm i

      - name: Build the project
        run: npm run build

      - name: Prepare clean plugin package
        run: |
          WORKDIR="$RUNNER_TEMP/infinite-uploads"
          rm -rf "$WORKDIR"
          mkdir -p "$WORKDIR"
          
          # Copy everything into the temp dir
          cp -a . "$WORKDIR/"
          
          cd "$WORKDIR"
          
          # Remove development-only files
          find . -type d -name "node_modules" -exec rm -rf {} +
          find . -type f -name ".distignore" -delete
          find . -type f -name ".gitattributes" -delete
          find . -type f -name ".gitignore" -delete
          find . -type f -name "composer.lock" -delete
          find . -type f -name "composer.json" -delete
          find . -type f -name "composer-dev.json" -delete
          find . -type f -name "LICENSE.txt" -delete
          find . -type f -name "README.md" -delete
          find . -type f -name "phpunit.xml" -delete
          find . -type f -name "phpunit.xml.dist" -delete
          find . -type f -name "package.json" -delete
          find . -type f -name "package-lock.json" -delete
          find . -type f -name "readme.md" -delete
          find . -type f -name "gulpfile.js" -delete
          find . -type f -name "build-aws3.sh" -delete
          find . -type f -name "webpack.config.js" -delete
          find . -type d -name "tests" -exec rm -rf {} +
          find . -type d -name "bin" -exec rm -rf {} +
          find . -mindepth 1 -name ".*" -exec rm -rf {} +
          
          # Zip it from within the runner temp
          zip -r "$RUNNER_TEMP/infinite-uploads-${{ steps.vars.outputs.version }}.zip" .

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: infinite-uploads-${{ steps.vars.outputs.version }}
          path: ${{ runner.temp }}/infinite-uploads-${{ steps.vars.outputs.version }}.zip
          retention-days: 5

      - name: Extract changelog from readme.txt
        id: changelog
        run: |
          VERSION=${{ steps.vars.outputs.version }}
          # Extract lines starting from version header until the next version header
          CHANGELOG=$(awk -v ver="$VERSION" '
            BEGIN { found=0 }
            /^[0-9]+\.[0-9]+(\.[0-9]+){0,2}/ {
              if ($1 == ver) { found=1; next }
              if (found) exit
            }
            found { print }
          ' readme.txt)

          # Export changelog to GitHub output
          echo "log<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGELOG" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.vars.outputs.version }}
          release_name: Release ${{ steps.vars.outputs.version }}
          body: ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ runner.temp }}/infinite-uploads-${{ steps.vars.outputs.version }}.zip
          asset_name: infinite-uploads.zip
          asset_content_type: application/zip