name: Build and ZIP WordPress Plugin

on:
  workflow_dispatch:
    inputs:
      tag_path:
        description: "Tag path (e.g. infiniteuploads/3.0.2)"
        required: true

jobs:
  build-and-zip:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js (if needed)
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies and build plugin
        run: |
          npm ci
          npm run build

      - name: Extract version and create ZIP
        run: |
          TAG_PATH="${{ github.event.inputs.tag_path }}"
          VERSION="${TAG_PATH##*/}"  # Extracts '3.0.2' from 'infiniteuploads/3.0.2'
          PLUGIN_SLUG="infinite-uploads"
          ZIP_NAME="${PLUGIN_SLUG}-v${VERSION}.zip"

          echo "Extracted version: $VERSION"
          echo "ZIP will be named: $ZIP_NAME"

          # Create a clean temp folder for the plugin
          mkdir "$PLUGIN_SLUG"

          # Copy plugin files into infinite-uploads/ folder
          rsync -av ./ "$PLUGIN_SLUG/" \
            --exclude=".git" \
            --exclude="node_modules" \
            --exclude=".github" \
            --exclude="*.zip" \
            --exclude="$PLUGIN_SLUG"

          # Create the versioned ZIP in the root directory
          zip -r "$ZIP_NAME" "$PLUGIN_SLUG"

      - name: Commit ZIP file to repo root
        run: |
          TAG_PATH="${{ github.event.inputs.tag_path }}"
          VERSION="${TAG_PATH##*/}"
          ZIP_NAME="infinite-uploads-v${VERSION}.zip"

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add "$ZIP_NAME"
          git commit -m "Add ZIP: $ZIP_NAME"
          git push
