name: Deploy to WordPress.org

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Install Subversion (SVN)
      - name: Install Subversion
        run: sudo apt-get update && sudo apt-get install subversion -y

    # Step 2.1: Increase SVN HTTP timeout to 1 hour
      - name: Increase SVN timeout
        run: |
          mkdir -p ~/.subversion
          echo "[global]" >> ~/.subversion/servers
          echo "http-timeout = 3600" >> ~/.subversion/servers
          
      # Step 3: Build the plugin
      - name: Build the plugin
        run: |
          npm install
          npm run build

      # Step 4: Deploy to WordPress.org Plugin Repository
      - name: WordPress Plugin Deploy
        id: deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        with:
          generate-zip: true
        env:
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}

      # Step 5: Upload release asset
      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ steps.deploy.outputs.zip-path }}
          asset_name: ${{ github.event.repository.name }}.zip
          asset_content_type: application/zip
